### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by timmy3000**
screencapture-127-0-0-1-5173-documentation-2022-11-12-14_48_15

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
@Chimexx @timmy3000 that url is invalid o

**Comment by PhilemonBrain** [comment]
and we could have shown where the token is added in the request
@Chimexx

**Comment by Chimexx** [comment]
> and we could have shown where the token is added in the request
> @Chimexx 

I sent him 3 images, one was about header, another about query params.

**Comment by Chimexx** [comment]
> @Chimexx @timmy3000 that url is invalid o
> 

Should it valid? I made it as a sample

**Pull request closed without merging**
