### PR TITLE
added password validation

### PR DESCRIPTION
**Pull request by CreedTech**

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
@pablo-clueless @taiwoAkindele review this please

**Comment by pablo-clueless** [comment]
> @pablo-clueless @taiwoAkindele review this please
> 

There's a password validation check already, the REGEx written by Taiwo covers all checks including minimum and maximum length, special characters, uppercase and lowercase.

**Comment by CreedTech** [comment]
> > @pablo-clueless @taiwoAkindele review this please
> > 
> 
> There's a password validation check already, the REGEx written by Taiwo covers all checks including minimum and maximum length, special characters, uppercase and lowercase.

It was only displaying a single error message and brain asked me to make the error messages clearer

**Comment by pablo-clueless** [comment]
> > > @pablo-clueless @taiwoAkindele review this please
> > > 
> > 
> > There's a password validation check already, the REGEx written by Taiwo covers all checks including minimum and maximum length, special characters, uppercase and lowercase.
> 
> It was only displaying a single error message and brain asked me to make the error messages clearer

Ok.

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
