### PR TITLE
Login-signup button on responsive screen

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
@Charles1403 please always drop the screenshot here, thanks. 
But You forgot the X(close) button on small screen used to close the component

**Comment by ghost** [comment]
Screenshot 2022-10-26 at 14 42 01
Screenshot 2022-10-26 at 14 42 49


1. The first screenshot is when the hamburger menu is closed
2. The second screenshot is when the hamburger menu is open

**Comment by ghost** [comment]
1. Screenshot 2022-10-26 at 14 59 14
2. Screenshot 2022-10-26 at 15 00 54

The first image is the screenshot of the hamburger
menu before the user is logged in
The second image is the screenshot of the hamburger
menu after the user has logged in

**Comment by PhilemonBrain** [comment]
@Charles1403 thanks for the update

**Pull request merged**
