### PR TITLE
subscription Table done

### PR DESCRIPTION
**Pull request by taiwoAkindele**
Subscription Tableau Done
subscription Table

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
@taiwoAkindele can u reduce the width. let it start from the left end of the search button to the right end of the Add API Button

**Comment by PhilemonBrain** [comment]
please change the color of that button as well @taiwoAkindele . either make it white and black like the add api button or like the green add endpoint button

**Comment by taiwoAkindele** [comment]
navbar

**Comment by taiwoAkindele** [comment]
sub table fixes

**Pull request merged**
