### PR TITLE
Add icons and changed red color

### PR DESCRIPTION
**Pull request by Zelipha**
- Changed the red color
Screenshot from 2022-11-17 21-22-05

- Added Icons 

Screenshot from 2022-11-17 21-59-05

### CODE REVIEW

**Comment by Chimexx** [comment]
I think I prefer this shade of  green 
image

Red here is better too, but used for dangerious actions like delete
image

we can use grey or  very light blue for unsubscribe button, fonts can be bigger too

**Comment by Zelipha** [comment]
> I think I prefer this shade of green image
> 
> Red here is better too, but used for dangerious actions like delete image
> 
> we can use grey or very light blue for unsubscribe button, fonts can be bigger too

Screenshot from 2022-11-19 19-29-57

- Made the changes you suggested
- @PhilemonBrain the copy also seems to work, i just commented the alert because it is after the alert confirmation that the link seem to copy

**Comment by PhilemonBrain** [comment]
@Chimexx @timmy3000 what do you guys think about this?

**Comment by Chimexx** [comment]
@Zelipha, the color you used is it the same as the one I posted? Plz verify... Yours is too light

**Comment by Chimexx** [comment]
Or simply use the green comment button here on github

**Comment by Zelipha** [comment]
> 

@Chimexx yes it is, I used a color picker and used the image hex colors. You can verify

**Comment by Zelipha** [comment]
hhhhhh

**Comment by Zelipha** [comment]
c

**Comment by Zelipha** [comment]
> Or simply use the green comment button here on github

There we go
Screenshot from 2022-11-23 13-20-35

**Comment by Zelipha** [comment]
- Suggested colors by @timmy3000 
 
Screenshot from 2022-11-23 21-38-39

**Pull request merged**
