### PR TITLE
adding a popup notification function

### PR DESCRIPTION
**Pull request by Bit-Han**
- Added React-toastify package 
- implement a common popup notification

### CODE REVIEW

**Review by pablo-clueless — COMMENTED** [review]
Where is the toast being used?? I can't see any usage.

**Review by taiwoAkindele — APPROVED** [review]

**Comment by Bit-Han** [comment]
Thank You Taiwo for adding Demo and conflict fix

**Comment by PhilemonBrain** [comment]
@Bit-Han please fix the conflicts

**Comment by PhilemonBrain** [comment]
@taiwoAkindele has these been reviewed by you??

**Pull request merged**
