### PR TITLE
Update Documentation Page

### PR DESCRIPTION
**Pull request by timmy3000**
screencapture-127-0-0-1-5173-documentation-2022-11-16-10_49_49

### CODE REVIEW

**Comment by timmy3000** [comment]
screencapture-127-0-0-1-5173-documentation-2022-11-16-14_36_23

**Comment by timmy3000** [comment]
screencapture-127-0-0-1-5173-documentation-2022-11-17-13_09_57

**Comment by PhilemonBrain** [comment]
@Chimexx this is not the url... the url is /api-request

**Comment by timmy3000** [comment]
screencapture-127-0-0-1-5173-documentation-2022-11-20-18_11_45

**Pull request merged**
