### PR TITLE
Add descriptive heading on inputs

### PR DESCRIPTION
**Pull request by Zelipha**
- Let me know if in case of any changes @PhilemonBrain 
Screenshot from 2023-02-08 20-10-43

- The error pop-up was already working

Screenshot from 2023-02-08 20-21-37

### CODE REVIEW

**Comment by PhilemonBrain** [comment]
Thanks @Zelipha.

For the placeholder use this values instead, 
Headers => e.g Authorization
Body => e.g name
Query => e.g userId

**Comment by Zelipha** [comment]
- Placeholders changed
Screenshot from 2023-02-08 22-19-38

**Comment by PhilemonBrain** [comment]
Thanks @Zelipha. Please add `e.g`

**Comment by PhilemonBrain** [comment]
B4 the placeholders

**Pull request merged**
