### PR TITLE
Notification

### PR DESCRIPTION
**Pull request by CreedTech**
* changed notification design
* Testing of notification functionality

### CODE REVIEW

**Review by taiwoAkindele — CHANGES_REQUESTED** [review]
The console is full of socket errors. Checked and the error is from socket.io, happens when socket is down. There's nothing we can do except to hide it from the console

**Comment by CreedTech** [comment]
I cleared all errors
And I removed anything that might cause socket errors
But I'll check again though

**Comment by PhilemonBrain** [comment]
@CreedTech how far? with these errors

**Comment by CreedTech** [comment]
I have handled the notification error
It's not throwing error when there's no connection established @PhilemonBrain

**Review by pablo-clueless — CHANGES_REQUESTED** [review]
Can you abstract the logic into a separate file?? This file is too lenghty. Do the logic separately, and return something from it and let's use it as a hook instead.

**Comment by CreedTech** [comment]
I'll try it

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
